include ../../Config/Makefile/shared.mk

.PHONY: mockolo
mockolo: $(MOCKOLO)
	$(MOCKOLO) \
		--sourcedirs ./UILogicInterface/Sources \
		--destination ./UILogicInterface/Sources/Generated/zzz.mockolo.swift \
		--macro DEBUG