include ../../Config/Makefile/shared.mk

.PHONY: mockolo
mockolo: $(MOCKOLO)
	$(MOCKOLO) \
		--sourcedirs ./Domain/Sources \
		--destination ./Domain/Sources/Generated/zzz.mockolo.swift \
		--macro DEBUG