include ../../Config/Makefile/shared.mk

.PHONY: mockolo
mockolo: $(MOCKOLO)
	$(MOCKOLO) \
		--sourcedirs ./UseCaseInterface/Sources \
		--destination ./UseCaseInterface/Sources/Generated/zzz.mockolo.swift \
		--macro DEBUG