name: Publish Answers

on:
  push:
    branches: [public-answer]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Username and Authentication
        run: |
          git config --global user.name abematviosbot
          git config --global user.email ios_bot@abema.tv
          cat <<- EOS >> $HOME/.netrc
          machine github.com
          login abematviosbot
          password ${{ secrets.BOT_GITHUB_TOKEN }}
          EOS
          chmod 600 $HOME/.netrc

      - name: Publish Answers
        run: |
          set -eux
          git remote add public https://github.com/abema/abema-ios-tutorial-public
          git fetch public
          COMMITS=$(git log -n $NUMBER_OF_ANSWERS --pretty=%H --reverse)
          git checkout -b answer-base public/master
          INDEX=0
          for COMMIT in $COMMITS; do
            INDEX=$(expr $INDEX + 1)
            git checkout -b answer-$INDEX
            git cherry-pick $COMMIT
            git push -f public HEAD
          done
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          NUMBER_OF_ANSWERS: 4
